const Data = [
    {
        id: "1",
        nameOfTrail: "The Rockwall Trail",
        trailDescription: "Amazing trail featuring lakes, mountains, wildlife",
        country: "Canada",
        parkLocation: "Kootenay National Park",
        stateOrProvince: "British Columbia",
        permitRequired: "Yes",
        hikingPermitCost: "$10.02",
        permitRequiredToEnterPark: "Yes",
        parkPermitCost: "$10.50",
        campingPermitRequired: "Yes",
        campingPermitCostPerSite: "$10.50",
        lengthInMiles: "33.7 Miles",
        lengthInKM: "54.1KM",
        routeType: "Point to point",
        distanceBetweenFinishingSpotAndStartingSpotMiles: "8 Miles",
        distanceBetweenFinishingSpotAndStartingSpotKM: "12.8KM",
        distanceBetweenFinishingSpotAndStartingSpotMinInCar: "9 Minutes",
        elevationGainFt: "9,343 Feet",
        elevationGainMeters: "2,848M",
        elevationLossFt: "6627 Feet",
        elevationLossMeters: "2020M",
        bestHikingWindow: "June through September",
        bestHikingWindowAverageLowTemp: "52 Degrees fahrenheit",
        bestHikingWindowAverageHighTemp: "72 Degrees fahrenheit",
        recommendedTimeSpent: "3-5 Days",
        recommendStartingSpot: "Paint Pots trail head",
        recommendedFinishingSpot: "Floe Lake trail head",
        recommendStartingSpotCoordinates: "51.169487, -116.147549",
        recommendedEndingSpotCoordinates: "51.080970, -116.054949",
        isItCommonToHitchHike: "yes",
        recommendRoute: {
            day1: "Sleep at Helmet Falls campground",
            day2: "Sleep at Tumbling Creek campground",
            day3: "Sleep at Floe Lake campground",
        },
        highlightsAndFeatures: "Floe Lake, massive mountains, wildlife, valleys",
        howFastDoPermitsSellOut: "Usually within the first hour of being available",
        permitGatheringInstructions: "Log on early and get in the queue. Go as fast as you can!",
        permitWebsite: "https://reservation.pc.gc.ca/Banff,KootenayandYohoBackcountry",
        linkToOfficialWebsite: "https://www.pc.gc.ca/en/pn-np/bc/kootenay/activ/arrierepays-backcountry",
        waterSupplyInformation: "There is plenty of water along the whole route",
        maxElevation: "7662 Feet",
        lowestElevation: "4331 Feet",
        areThereBears: "Yes",
        wildlifeSpottingOpportunities: "black and grizzly bears, elk, deer, moose, bighorn sheep, mountain goats, coyotes, wolves, owls, snowshoe hares, ground squirrels, migratory birds including bald and golden eagles, songbirds, ducks and hawks.",
        firesAllowed: "",
        dogsAllowed: "",
        howToGetThere: "",
        helpfulTips: "", 
        linkToWeather: "",
        linkToAllTrails: "",
        linkToGoodGuide: "",
        linkToPictures: "",
    }, 
    {
        id: "2",
        nameOfTrail: "The Skyline Trail",
        trailDescription: "Amazing trail leading you up and over the mountains of Jasper National Park",
        country: "Canada",
        parkLocation: "Jasper National Park",
        stateOrProvince: "Alberta",
        permitRequired: "Yes",
        hikingPermitCost: "$10.50",
        permitRequiredToEnterPark: "Yes",
        parkPermitCost: "$10.50",
        campingPermitRequired: "Yes",
        campingPermitCostPerSite: "$10.50",
        lengthInMiles: "27.9 Miles",
        lengthInKM: "44.9KM",
        routeType: "Point to point",
        distanceBetweenFinishingSpotAndStartingSpotMiles: "24 Miles",
        distanceBetweenFinishingSpotAndStartingSpotKM: "39KM",
        distanceBetweenFinishingSpotAndStartingSpotMinInCar: "37 minutes",
        elevationGainFt: "5,331 Feet",
        elevationGainMeters: "1,625M",
        elevationLossFt: "6332 Feet",
        elevationLossMeters: "1930M",
        bestHikingWindow: "June through September",
        bestHikingWindowAverageLowTemp: "40 degrees fahrenheit",
        bestHikingWindowAverageHighTemp: "70 degrees fahrenheit",
        recommendedTimeSpent: "3-5 Days",
        recommendStartingSpot: "Maligne Lake",
        recommendedFinishingSpot: "Skyline Trail head",
        recommendStartingSpotCoordinates: "52.726017, -117.645480",
        recommendedEndingSpotCoordinates: "52.914288, -118.001346",
        isItCommonToHitchHike: "Not super common, but possible. There is also a shuttle at https://www.jasper.travel/experiences/maligne-valley-hikers-shuttle/",
        recommendRoute: {
            day1: "Sleep at Snowbowl campground",
            day2: "Sleep at Curator campground",
            day3: "Sleep at Tekarra campground",
        },
        highlightsAndFeatures: "Amazing views of Jasper National Park, hiking over peaks, and lakes",
        howFastDoPermitsSellOut: "Usually within the first hour of being available",
        permitGatheringInstructions: "Log on early and get in the queue. Go as fast as you can!",
        permitWebsite: "https://reservation.pc.gc.ca/Jasper/BackcountryCampsites/SkylineTrail?Map",
        linkToOfficialWebsite: "https://www.pc.gc.ca/en/pn-np/ab/jasper/activ/passez-stay/arrierepays-backcountry/sugg-sentiers_trip-ideas/Skyline",
        waterSupplyInformation: "Water is plentiful along this trail and easily accessible from small streams.",
        maxElevation: "8,238ft",
        lowestElevation: "3,847ft",
        areThereBears: "Yes",
        wildlifeSpottingOpportunities: "caribou, elk, moose, mountain goats, bighorn sheep, bears and wolves",
        firesAllowed: "",
        dogsAllowed: "",
        howToGetThere: "",
        helpfulTips: "", 
        linkToWeather: "",
        linkToAllTrails: "",
        linkToGoodGuide: "",
        linkToPictures: "",
    },
    {
        id: "3",
        nameOfTrail: "Kings Peak",
        trailDescription: "This is the highest peak in Utah!",
        country: "USA",
        parkLocation: "Uinta National Forest",
        stateOrProvince: "Utah",
        hikingPermitRequired: "No",
        permitCost: "N/a",
        permitRequiredToEnterPark: "No",
        parkPermitCost: "N/a",
        campingPermitRequired: "Yes",
        campingPermitCostPerSite: "$10.50",
        lengthInMiles: "27.8 Miles",
        lengthInKM: "44.7KM",
        routeType: "Out and Back",
        distanceBetweenFinishingSpotAndStartingSpotMiles: "0M",
        distanceBetweenFinishingSpotAndStartingSpotKM: "0KM",
        distanceBetweenFinishingSpotAndStartingSpotMinInCar: "0 Minutes",
        elevationGainFt: "5,160 Feet",
        elevationGainMeters: "1,573M",
        elevationLossFt: "5,160 Feet",
        elevationLossMeters: "1,573M",
        bestHikingWindow: "June through September",
        bestHikingWindowAverageLowTemp: "44 degrees fahrenheit",
        bestHikingWindowAverageHighTemp: "70 degrees fahrenheit",
        recommendedTimeSpent: "2-3 Days",
        recommendStartingSpot: "Henry's Fork Trail head",
        recommendedFinishingSpot: "Floe Lake trail head",
        recommendStartingSpotCoordinates: "40.909393, -110.330919",
        recommendedEndingSpotCoordinates: "40.909393, -110.330919",
        isItCommonToHitchHike: "Not Necessary",
        recommendRoute: {
            day1: "Sleep at Dollar Lake campground",
            day2: "Sleep at Dollar Lake campground",
        },
        highlightsAndFeatures: "",
        howFastDoPermitsSellOut: "N/a",
        permitGatheringInstructions: "N/a",
        permitWebsite: "N/a",
        linkToOfficialWebsite: "N/a",
        waterSupplyInformation: "Many creeks and lakes along the way",
        maxElevation: "13,528 Feet",
        lowestElevation: "9,451 Feet",
        areThereBears: "Yes",
        wildlifeSpottingOpportunities: "elk, mule deer, moose, mountain goat, coyote, black bear, bighorn sheep, ptarmigan, river otter, pine marten, cougar, and 75 percent of Utah's bird species",
        firesAllowed: "",
        dogsAllowed: "",
        howToGetThere: "",
        helpfulTips: "", 
        linkToWeather: "",
        linkToAllTrails: "",
        linkToGoodGuide: "",
        linkToPictures: "",
    },
    {
        id: "4",
        nameOfTrail: "Patagonia W Circuit",
        trailDescription: "A very popular trip in Patagonia",
        country: "Chile",
        parkLocation: "Torres Del Paine",
        stateOrProvince: "última Esperanza",
        hikingPermitRequired: "No",
        permitCost: "N/a",
        permitRequiredToEnterPark: "Yes",
        parkPermitCost: "",
        campingPermitRequired: "Yes",
        campingPermitCostPerSite: "$10.50",
        lengthInMiles: "62 Miles",
        lengthInKM: "54.1KM",
        routeType: "Out and Back",
        distanceBetweenFinishingSpotAndStartingSpotMiles: "",
        distanceBetweenFinishingSpotAndStartingSpotKM: "12.8KM",
        distanceBetweenFinishingSpotAndStartingSpotMinInCar: "9",
        elevationGainFt: "9,343 Feet",
        elevationGainMeters: "2,848M",
        elevationLossFt: "",
        elevationLossMeters: "",
        bestHikingWindow: "November to March",
        bestHikingWindowAverageLowTemp: "43 degrees Fahrenheit",
        bestHikingWindowAverageHighTemp: "63 degrees Fahrenheit",
        recommendedTimeSpent: "4-7 Days",
        recommendStartingSpot: "Paint Pots trail head",
        recommendedFinishingSpot: "Floe Lake trail head",
        recommendStartingSpotCoordinates: "",
        recommendedEndingSpotCoordinates: "",
        isItCommonToHitchHike: "yes",
        recommendRoute: {
            day1: "Sleep at __ campground",
            day2: "Sleep at __ campground",
            day3: "Sleep at __ campground",
            day4: "Sleep at __ campground",
        },
        highlightsAndFeatures: "",
        howFastDoPermitsSellOut: "Usually within the first hour of being available",
        permitGatheringInstructions: "Log on early and get in the queue. Go as fast as you can!",
        permitWebsite: "https://reservation.pc.gc.ca/Banff,KootenayandYohoBackcountry",
        linkToOfficialWebsite: "https://www.pc.gc.ca/en/pn-np/bc/kootenay/activ/arrierepays-backcountry",
        waterSupplyInformation: "",
        maxElevation: "",
        lowestElevation: "",
        areThereBears: "",
        wildlifeSpottingOpportunities: "",    
        firesAllowed: "",
        dogsAllowed: "",
        howToGetThere: "",
        helpfulTips: "", 
        linkToWeather: "",
        linkToAllTrails: "",
        linkToGoodGuide: "",
        linkToPictures: "",
    },
    {
        id: "5",
        nameOfTrail: "Grand Canyon Rim to Rim",
        trailDescription: "Hike down into the Grand Canyon and back up!",
        country: "USA",
        parkLocation: "Grand Canyon National Park",
        stateOrProvince: "Arizona",
        hikingPermitRequired: "False",
        permitCost: "",
        permitRequiredToEnterPark: "No",
        parkPermitCost: "",
        campingPermitRequired: "Yes",
        campingPermitCostPerSite: "$10.50",
        lengthInMiles: "33.7 Miles",
        lengthInKM: "54.1KM",
        routeType: "Out and Back",
        distanceBetweenFinishingSpotAndStartingSpotMiles: "",
        distanceBetweenFinishingSpotAndStartingSpotKM: "12.8KM",
        distanceBetweenFinishingSpotAndStartingSpotMinInCar: "9",
        elevationGainFt: "9,343 Feet",
        elevationGainMeters: "2,848M",
        elevationLossFt: "",
        elevationLossMeters: "",
        bestHikingWindow: "June through September",
        bestHikingWindowAverageLowTemp: "",
        bestHikingWindowAverageHighTemp: "",
        recommendedTimeSpent: "3-5 Days",
        recommendStartingSpot: "Paint Pots trail head",
        recommendedFinishingSpot: "Floe Lake trail head",
        recommendStartingSpotCoordinates: "",
        recommendedEndingSpotCoordinates: "",
        isItCommonToHitchHike: "yes",
        recommendRoute: {
            day1: "Sleep at __ campground",
            day2: "Sleep at __ campground",
            day3: "Sleep at __ campground",
            day4: "Sleep at __ campground",
        },
        highlightsAndFeatures: "",
        howFastDoPermitsSellOut: "Usually within the first hour of being available",
        permitGatheringInstructions: "Log on early and get in the queue. Go as fast as you can!",
        permitWebsite: "https://reservation.pc.gc.ca/Banff,KootenayandYohoBackcountry",
        linkToOfficialWebsite: "https://www.pc.gc.ca/en/pn-np/bc/kootenay/activ/arrierepays-backcountry",
        waterSupplyInformation: "",
        maxElevation: "",
        lowestElevation: "",
        areThereBears: "",
        wildlifeSpottingOpportunities: "",
        firesAllowed: "",
        dogsAllowed: "",
        howToGetThere: "",
        helpfulTips: "", 
        linkToWeather: "",
        linkToAllTrails: "",
        linkToGoodGuide: "",
        linkToPictures: "",
    },
    {
        id: "6",
        nameOfTrail: "Teton Crest Trail",
        trailDescription: "Hike through the amazing Teton Mountain Range!",
        country: "USA",
        parkLocation: "Teton National Park",
        stateOrProvince: "Wyoming",
        hikingPermitRequired: "False",
        permitCost: "",
        permitRequiredToEnterPark: "No",
        parkPermitCost: "",
        campingPermitRequired: "Yes",
        campingPermitCostPerSite: "$10.50",
        lengthInMiles: "33.7 Miles",
        lengthInKM: "54.1KM",
        routeType: "Out and Back",
        distanceBetweenFinishingSpotAndStartingSpotMiles: "",
        distanceBetweenFinishingSpotAndStartingSpotKM: "12.8KM",
        distanceBetweenFinishingSpotAndStartingSpotMinInCar: "9",
        elevationGainFt: "9,343 Feet",
        elevationGainMeters: "2,848M",
        elevationLossFt: "",
        elevationLossMeters: "",
        bestHikingWindow: "June through September",
        bestHikingWindowAverageLowTemp: "",
        bestHikingWindowAverageHighTemp: "",
        recommendedTimeSpent: "3-5 Days",
        recommendStartingSpot: "Paint Pots trail head",
        recommendedFinishingSpot: "Floe Lake trail head",
        recommendStartingSpotCoordinates: "",
        recommendedEndingSpotCoordinates: "",
        isItCommonToHitchHike: "yes",
        recommendRoute: {
            day1: "Sleep at __ campground",
            day2: "Sleep at __ campground",
            day3: "Sleep at __ campground",
            day4: "Sleep at __ campground",
        },
        highlightsAndFeatures: "",
        howFastDoPermitsSellOut: "Usually within the first hour of being available",
        permitGatheringInstructions: "Log on early and get in the queue. Go as fast as you can!",
        permitWebsite: "https://reservation.pc.gc.ca/Banff,KootenayandYohoBackcountry",
        linkToOfficialWebsite: "https://www.pc.gc.ca/en/pn-np/bc/kootenay/activ/arrierepays-backcountry",
        waterSupplyInformation: "",
        maxElevation: "",
        lowestElevation: "",
        areThereBears: "",
        wildlifeSpottingOpportunities: "",
        firesAllowed: "",
        dogsAllowed: "",
        howToGetThere: "",
        helpfulTips: "", 
        linkToWeather: "",
        linkToAllTrails: "",
        linkToGoodGuide: "",
        linkToPictures: "",
    },
    {
        id: "7",
        nameOfTrail: "Titcomb Basin",
        trailDescription: "Hike through the amazing Wind River Mountain Range",
        country: "USA",
        parkLocation: "Grand Canyon National Park",
        stateOrProvince: "Arizona",
        hikingPermitRequired: "False",
        permitCost: "",
        permitRequiredToEnterPark: "No",
        parkPermitCost: "",
        campingPermitRequired: "Yes",
        campingPermitCostPerSite: "$10.50",
        lengthInMiles: "33.7 Miles",
        lengthInKM: "54.1KM",
        routeType: "Out and Back",
        distanceBetweenFinishingSpotAndStartingSpotMiles: "",
        distanceBetweenFinishingSpotAndStartingSpotKM: "12.8KM",
        distanceBetweenFinishingSpotAndStartingSpotMinInCar: "9",
        elevationGainFt: "9,343 Feet",
        elevationGainMeters: "2,848M",
        elevationLossFt: "",
        elevationLossMeters: "",
        bestHikingWindow: "June through September",
        bestHikingWindowAverageLowTemp: "",
        bestHikingWindowAverageHighTemp: "",
        recommendedTimeSpent: "3-5 Days",
        recommendStartingSpot: "Paint Pots trail head",
        recommendedFinishingSpot: "Floe Lake trail head",
        recommendStartingSpotCoordinates: "",
        recommendedEndingSpotCoordinates: "",
        isItCommonToHitchHike: "yes",
        recommendRoute: {
            day1: "Sleep at __ campground",
            day2: "Sleep at __ campground",
            day3: "Sleep at __ campground",
            day4: "Sleep at __ campground",
        },
        highlightsAndFeatures: "",
        howFastDoPermitsSellOut: "Usually within the first hour of being available",
        permitGatheringInstructions: "Log on early and get in the queue. Go as fast as you can!",
        permitWebsite: "https://reservation.pc.gc.ca/Banff,KootenayandYohoBackcountry",
        linkToOfficialWebsite: "https://www.pc.gc.ca/en/pn-np/bc/kootenay/activ/arrierepays-backcountry",
        waterSupplyInformation: "",
        maxElevation: "",
        lowestElevation: "",
        areThereBears: "",
        wildlifeSpottingOpportunities: "",
        firesAllowed: "",
        dogsAllowed: "",
        howToGetThere: "",
        helpfulTips: "", 
        linkToWeather: "",
        linkToAllTrails: "",
        linkToGoodGuide: "",
        linkToPictures: "",
    },
    {
        id: "8",
        nameOfTrail: "Buckskin Gulch",
        trailDescription: "Hike through the longest slot canyon in the world!",
        country: "USA",
        parkLocation: "",
        stateOrProvince: "Utah",
        hikingPermitRequired: "False",
        permitCost: "",
        permitRequiredToEnterPark: "No",
        parkPermitCost: "",
        campingPermitRequired: "Yes",
        campingPermitCostPerSite: "$10.50",
        lengthInMiles: "33.7 Miles",
        lengthInKM: "54.1KM",
        routeType: "Out and Back",
        distanceBetweenFinishingSpotAndStartingSpotMiles: "",
        distanceBetweenFinishingSpotAndStartingSpotKM: "12.8KM",
        distanceBetweenFinishingSpotAndStartingSpotMinInCar: "9",
        elevationGainFt: "9,343 Feet",
        elevationGainMeters: "2,848M",
        elevationLossFt: "",
        elevationLossMeters: "",
        bestHikingWindow: "June through September",
        bestHikingWindowAverageLowTemp: "",
        bestHikingWindowAverageHighTemp: "",
        recommendedTimeSpent: "3-5 Days",
        recommendStartingSpot: "Paint Pots trail head",
        recommendedFinishingSpot: "Floe Lake trail head",
        recommendStartingSpotCoordinates: "",
        recommendedEndingSpotCoordinates: "",
        isItCommonToHitchHike: "yes",
        recommendRoute: {
            day1: "Sleep at __ campground",
            day2: "Sleep at __ campground",
            day3: "Sleep at __ campground",
            day4: "Sleep at __ campground",
        },
        highlightsAndFeatures: "",
        howFastDoPermitsSellOut: "Usually within the first hour of being available",
        permitGatheringInstructions: "Log on early and get in the queue. Go as fast as you can!",
        permitWebsite: "https://reservation.pc.gc.ca/Banff,KootenayandYohoBackcountry",
        linkToOfficialWebsite: "https://www.pc.gc.ca/en/pn-np/bc/kootenay/activ/arrierepays-backcountry",
        waterSupplyInformation: "",
        maxElevation: "",
        lowestElevation: "",
        areThereBears: "",
        wildlifeSpottingOpportunities: "",
        firesAllowed: "",
        dogsAllowed: "",
        howToGetThere: "",
        helpfulTips: "", 
        linkToWeather: "",
        linkToAllTrails: "",
        linkToGoodGuide: "",
        linkToPictures: "",
    },
    {
        id: "9",
        nameOfTrail: "Inca trail",
        trailDescription: "Hike through the Peruvian jungle to see the famous Machu Pichu!",
        country: "Peru",
        parkLocation: "",
        stateOrProvince: "",
        hikingPermitRequired: "False",
        permitCost: "",
        permitRequiredToEnterPark: "No",
        parkPermitCost: "",
        campingPermitRequired: "Yes",
        campingPermitCostPerSite: "$10.50",
        lengthInMiles: "33.7 Miles",
        lengthInKM: "54.1KM",
        routeType: "Out and Back",
        distanceBetweenFinishingSpotAndStartingSpotMiles: "",
        distanceBetweenFinishingSpotAndStartingSpotKM: "12.8KM",
        distanceBetweenFinishingSpotAndStartingSpotMinInCar: "9",
        elevationGainFt: "9,343 Feet",
        elevationGainMeters: "2,848M",
        elevationLossFt: "",
        elevationLossMeters: "",
        bestHikingWindow: "June through September",
        bestHikingWindowAverageLowTemp: "",
        bestHikingWindowAverageHighTemp: "",
        recommendedTimeSpent: "3-5 Days",
        recommendStartingSpot: "Paint Pots trail head",
        recommendedFinishingSpot: "Floe Lake trail head",
        recommendStartingSpotCoordinates: "",
        recommendedEndingSpotCoordinates: "",
        isItCommonToHitchHike: "yes",
        recommendRoute: {
            day1: "Sleep at __ campground",
            day2: "Sleep at __ campground",
            day3: "Sleep at __ campground",
            day4: "Sleep at __ campground",
        },
        highlightsAndFeatures: "",
        howFastDoPermitsSellOut: "Usually within the first hour of being available",
        permitGatheringInstructions: "Log on early and get in the queue. Go as fast as you can!",
        permitWebsite: "https://reservation.pc.gc.ca/Banff,KootenayandYohoBackcountry",
        linkToOfficialWebsite: "https://www.pc.gc.ca/en/pn-np/bc/kootenay/activ/arrierepays-backcountry",
        waterSupplyInformation: "",
        maxElevation: "",
        lowestElevation: "",
        areThereBears: "",
        wildlifeSpottingOpportunities: "",
        firesAllowed: "",
        dogsAllowed: "",
        howToGetThere: "",
        helpfulTips: "", 
        linkToWeather: "",
        linkToAllTrails: "",
        linkToGoodGuide: "",
        linkToPictures: "",
    },
    {
        id: "10",
        nameOfTrail: "Annapurna Circuit",
        trailDescription: "Hike through the amazing mountains of Nepal",
        country: "Nepal",
        parkLocation: "",
        stateOrProvince: "",
        hikingPermitRequired: "False",
        permitCost: "",
        permitRequiredToEnterPark: "No",
        parkPermitCost: "",
        campingPermitRequired: "Yes",
        campingPermitCostPerSite: "$10.50",
        lengthInMiles: "33.7 Miles",
        lengthInKM: "54.1KM",
        routeType: "Out and Back",
        distanceBetweenFinishingSpotAndStartingSpotMiles: "",
        distanceBetweenFinishingSpotAndStartingSpotKM: "12.8KM",
        distanceBetweenFinishingSpotAndStartingSpotMinInCar: "9",
        elevationGainFt: "9,343 Feet",
        elevationGainMeters: "2,848M",
        elevationLossFt: "",
        elevationLossMeters: "",
        bestHikingWindow: "June through September",
        bestHikingWindowAverageLowTemp: "",
        bestHikingWindowAverageHighTemp: "",
        recommendedTimeSpent: "3-5 Days",
        recommendStartingSpot: "Paint Pots trail head",
        recommendedFinishingSpot: "Floe Lake trail head",
        recommendStartingSpotCoordinates: "",
        recommendedEndingSpotCoordinates: "",
        isItCommonToHitchHike: "yes",
        recommendRoute: {
            day1: "Sleep at __ campground",
            day2: "Sleep at __ campground",
            day3: "Sleep at __ campground",
            day4: "Sleep at __ campground",
        },
        highlightsAndFeatures: "",
        howFastDoPermitsSellOut: "Usually within the first hour of being available",
        permitGatheringInstructions: "Log on early and get in the queue. Go as fast as you can!",
        permitWebsite: "https://reservation.pc.gc.ca/Banff,KootenayandYohoBackcountry",
        linkToOfficialWebsite: "https://www.pc.gc.ca/en/pn-np/bc/kootenay/activ/arrierepays-backcountry",
        waterSupplyInformation: "",
        maxElevation: "",
        lowestElevation: "",
        areThereBears: "",
        wildlifeSpottingOpportunities: "",
        firesAllowed: "",
        dogsAllowed: "",
        howToGetThere: "",
        helpfulTips: "", 
        linkToWeather: "",
        linkToAllTrails: "",
        linkToGoodGuide: "",
        linkToPictures: "",
    },
    ]
    
    export default Data

