const Data = [
    {
        id: "1",
        nameOfTrail: "The Rockwall Trail",
        trailDescription: "Amazing trail featuring lakes, mountains, wildlife",
        country: "Canada",
        parkLocation: "Kootenay National Park",
        stateOrProvince: "British Columbia",
        permitRequired: "True",
        hikingPermitCost: "$10.02",
        permitRequiredToEnterPark: "True",
        parkPermitCost: "$10.50",
        lengthInMiles: "33.7 Miles",
        lengthInKM: "54.1KM",
        routeType: "Point to point",
        distanceBetweenFinishingSpotAndStartingSpotMiles: "8 Miles",
        distanceBetweenFinishingSpotAndStartingSpotKM: "12.8KM",
        distanceBetweenFinishingSpotAndStartingSpotMinInCar: "9 Minutes",
        elevationGainFt: "9,343 Feet",
        elevationGainMeters: "2,848M",
        elevationLossFt: "6627 Feet",
        elevationLossMeters: "2020M",
        bestHikingWindow: "June through September",
        bestHikingWindowAverageLowTemp: "52 Degrees fahrenheit",
        bestHikingWindowAverageHighTemp: "72 Degrees fahrenheit",
        recommendedTimeSpent: "3-5 Days",
        recommendStartingSpot: "Paint Pots trail head",
        recommendedFinishingSpot: "Floe Lake trail head",
        recommendStartingSpotCoordinates: "51.169487, -116.147549",
        recommendedEndingSpotCoordinates: "51.080970, -116.054949",
        isItCommonToHitchHike: "yes",
        recommendRoute: {
            day1: "Sleep at Helmet Falls campground",
            day2: "Sleep at Tumbling Creek campground",
            day3: "Sleep at Floe Lake campground",
        },
        highlightsAndFeatures: "Floe Lake, massive mountains, wildlife, valleys",
        howFastDoPermitsSellOut: "Usually within the first hour of being available",
        permitGatheringInstructions: "Log on early and get in the queue. Go as fast as you can!",
        permitWebsite: "https://reservation.pc.gc.ca/Banff,KootenayandYohoBackcountry",
        linkToOfficialWebsite: "https://www.pc.gc.ca/en/pn-np/bc/kootenay/activ/arrierepays-backcountry",
        waterSupplyInformation: "There is plenty of water along the whole route",
        maxElevation: "7662 Feet",
        lowestElevation: "4331 Feet",
        areThereBears: "Yes",
        wildlifeSpottingOpportunities: "black and grizzly bears, elk, deer, moose, bighorn sheep, mountain goats, coyotes, wolves, owls, snowshoe hares, ground squirrels, migratory birds including bald and golden eagles, songbirds, ducks and hawks.",
    }, 
    {
        id: "2",
        nameOfTrail: "The Skyline Trail",
        trailDescription: "Amazing trail leading you up and over the mountains of Jasper National Park",
        country: "Canada",
        parkLocation: "Jasper National Park",
        stateOrProvince: "Alberta",
        permitRequired: "True",
        hikingPermitCost: "$10.50",
        permitRequiredToEnterPark: "Yes",
        parkPermitCost: "$10.50",
        lengthInMiles: "27.9 Miles",
        lengthInKM: "44.9KM",
        routeType: "Point to point",
        distanceBetweenFinishingSpotAndStartingSpotMiles: "24 Miles",
        distanceBetweenFinishingSpotAndStartingSpotKM: "39KM",
        distanceBetweenFinishingSpotAndStartingSpotMinInCar: "37 minutes",
        elevationGainFt: "5,331 Feet",
        elevationGainMeters: "1,625M",
        elevationLossFt: "",
        elevationLossMeters: "",
        bestHikingWindow: "June through September",
        bestHikingWindowAverageLowTemp: "40 degrees fahrenheit",
        bestHikingWindowAverageHighTemp: "70 degrees fahrenheit",
        recommendedTimeSpent: "3-5 Days",
        recommendStartingSpot: "Maligne Lake",
        recommendedFinishingSpot: "Skyline Trail head",
        recommendStartingSpotCoordinates: "52.726017, -117.645480",
        recommendedEndingSpotCoordinates: "52.914288, -118.001346",
        isItCommonToHitchHike: "Not super common, but possible. There is also a shuttle at https://www.jasper.travel/experiences/maligne-valley-hikers-shuttle/",
        recommendRoute: {
            day1: "Sleep at Snowbowl campground",
            day2: "Sleep at Curator campground",
            day3: "Sleep at Tekarra campground",
        },
        highlightsAndFeatures: "Amazing views of Jasper National Park, hiking over peaks, and lakes",
        howFastDoPermitsSellOut: "Usually within the first hour of being available",
        permitGatheringInstructions: "Log on early and get in the queue. Go as fast as you can!",
        permitWebsite: "https://reservation.pc.gc.ca/Jasper/BackcountryCampsites/SkylineTrail?Map",
        linkToOfficialWebsite: "https://www.pc.gc.ca/en/pn-np/ab/jasper/activ/passez-stay/arrierepays-backcountry/sugg-sentiers_trip-ideas/Skyline",
        waterSupplyInformation: "Water is plentiful along this trail and easily accessible from small streams.",
        maxElevation: "8,238ft",
        lowestElevation: "3,847ft",
        areThereBears: "Yes",
        wildlifeSpottingOpportunities: "caribou, elk, moose, mountain goats, bighorn sheep, bears and wolves",
    },
    {
        id: "3",
        nameOfTrail: "Kings Peak",
        trailDescription: "This is the highest peak in Utah!",
        country: "USA",
        parkLocation: "Uinta National Forest",
        stateOrProvince: "Utah",
        hikingPermitRequired: "False",
        permitCost: "",
        permitRequiredToEnterPark: "No",
        parkPermitCost: "",
        lengthInMiles: "33.7 Miles",
        lengthInKM: "54.1KM",
        routeType: "Out and Back",
        distanceBetweenFinishingSpotAndStartingSpotMiles: "",
        distanceBetweenFinishingSpotAndStartingSpotKM: "12.8KM",
        distanceBetweenFinishingSpotAndStartingSpotMinInCar: "9",
        elevationGainFt: "9,343 Feet",
        elevationGainMeters: "2,848M",
        elevationLossFt: "",
        elevationLossMeters: "",
        bestHikingWindow: "June through September",
        bestHikingWindowAverageLowTemp: "",
        bestHikingWindowAverageHighTemp: "",
        recommendedTimeSpent: "3-5 Days",
        recommendStartingSpot: "Paint Pots trail head",
        recommendedFinishingSpot: "Floe Lake trail head",
        recommendStartingSpotCoordinates: "",
        recommendedEndingSpotCoordinates: "",
        isItCommonToHitchHike: "yes",
        recommendRoute: {
            day1: "Sleep at __ campground",
            day2: "Sleep at __ campground",
            day3: "Sleep at __ campground",
            day4: "Sleep at __ campground",
        },
        highlightsAndFeatures: "",
        howFastDoPermitsSellOut: "Usually within the first hour of being available",
        permitGatheringInstructions: "Log on early and get in the queue. Go as fast as you can!",
        permitWebsite: "https://reservation.pc.gc.ca/Banff,KootenayandYohoBackcountry",
        linkToOfficialWebsite: "https://www.pc.gc.ca/en/pn-np/bc/kootenay/activ/arrierepays-backcountry",
        waterSupplyInformation: "",
        maxElevation: "",
        lowestElevation: "",
        areThereBears: "",
        wildlifeSpottingOpportunities: "",
    },
    {
        id: "4",
        nameOfTrail: "Patagonia W Trek",
        trailDescription: "A popular trip in Patagonia",
        country: "Chile",
        parkLocation: "Torres Del Paine",
        stateOrProvince: "última Esperanza",
        hikingPermitRequired: "False",
        permitCost: "",
        permitRequiredToEnterPark: "No",
        parkPermitCost: "",
        lengthInMiles: "33.7 Miles",
        lengthInKM: "54.1KM",
        routeType: "Out and Back",
        distanceBetweenFinishingSpotAndStartingSpotMiles: "",
        distanceBetweenFinishingSpotAndStartingSpotKM: "12.8KM",
        distanceBetweenFinishingSpotAndStartingSpotMinInCar: "9",
        elevationGainFt: "9,343 Feet",
        elevationGainMeters: "2,848M",
        elevationLossFt: "",
        elevationLossMeters: "",
        bestHikingWindow: "June through September",
        bestHikingWindowAverageLowTemp: "",
        bestHikingWindowAverageHighTemp: "",
        recommendedTimeSpent: "3-5 Days",
        recommendStartingSpot: "Paint Pots trail head",
        recommendedFinishingSpot: "Floe Lake trail head",
        recommendStartingSpotCoordinates: "",
        recommendedEndingSpotCoordinates: "",
        isItCommonToHitchHike: "yes",
        recommendRoute: {
            day1: "Sleep at __ campground",
            day2: "Sleep at __ campground",
            day3: "Sleep at __ campground",
            day4: "Sleep at __ campground",
        },
        highlightsAndFeatures: "",
        howFastDoPermitsSellOut: "Usually within the first hour of being available",
        permitGatheringInstructions: "Log on early and get in the queue. Go as fast as you can!",
        permitWebsite: "https://reservation.pc.gc.ca/Banff,KootenayandYohoBackcountry",
        linkToOfficialWebsite: "https://www.pc.gc.ca/en/pn-np/bc/kootenay/activ/arrierepays-backcountry",
        waterSupplyInformation: "",
        maxElevation: "",
        lowestElevation: "",
        areThereBears: "",
        wildlifeSpottingOpportunities: "",
    },
    {
        id: "5",
        nameOfTrail: "Grand Canyon Rim to Rim",
        trailDescription: "Hike down into the Grand Canyon and back up!",
        country: "USA",
        parkLocation: "Grand Canyon National Park",
        stateOrProvince: "Arizona",
        hikingPermitRequired: "False",
        permitCost: "",
        permitRequiredToEnterPark: "No",
        parkPermitCost: "",
        lengthInMiles: "33.7 Miles",
        lengthInKM: "54.1KM",
        routeType: "Out and Back",
        distanceBetweenFinishingSpotAndStartingSpotMiles: "",
        distanceBetweenFinishingSpotAndStartingSpotKM: "12.8KM",
        distanceBetweenFinishingSpotAndStartingSpotMinInCar: "9",
        elevationGainFt: "9,343 Feet",
        elevationGainMeters: "2,848M",
        elevationLossFt: "",
        elevationLossMeters: "",
        bestHikingWindow: "June through September",
        bestHikingWindowAverageLowTemp: "",
        bestHikingWindowAverageHighTemp: "",
        recommendedTimeSpent: "3-5 Days",
        recommendStartingSpot: "Paint Pots trail head",
        recommendedFinishingSpot: "Floe Lake trail head",
        recommendStartingSpotCoordinates: "",
        recommendedEndingSpotCoordinates: "",
        isItCommonToHitchHike: "yes",
        recommendRoute: {
            day1: "Sleep at __ campground",
            day2: "Sleep at __ campground",
            day3: "Sleep at __ campground",
            day4: "Sleep at __ campground",
        },
        highlightsAndFeatures: "",
        howFastDoPermitsSellOut: "Usually within the first hour of being available",
        permitGatheringInstructions: "Log on early and get in the queue. Go as fast as you can!",
        permitWebsite: "https://reservation.pc.gc.ca/Banff,KootenayandYohoBackcountry",
        linkToOfficialWebsite: "https://www.pc.gc.ca/en/pn-np/bc/kootenay/activ/arrierepays-backcountry",
        waterSupplyInformation: "",
        maxElevation: "",
        lowestElevation: "",
        areThereBears: "",
        wildlifeSpottingOpportunities: "",
    },
    ]
    
    export default Data


    /*more to add
    - Fires allowed
    - Dogs allowed
    - 

    */