let backpackingTrips = [
{
    nameOfTrail: "The Rockwall",
    trailDescription: "This is an awesome trail!",
    countryLocation: "Canada",
    parkLocation: "Kootenay National Park",
    stateOrProvince: "British Columbia",
    permitRequired: "True",
    permitCost: "",
    permitRequiredToEnterPark: "",
    parkPermitCost: "",
    lengthInMiles: "33.7 Miles",
    lengthInKM: "54.1KM",
    routeType: "Point to point",
    distanceBetweenFinishingSpotAndStartingSpotMiles: "",
    distanceBetweenFinishingSpotAndStartingSpotKM: "12.8KM",
    distanceBetweenFinishingSpotAndStartingSpotMinInCar: "9",
    elevationGainFt: "9,343 Feet",
    elevationGainMeters: "2,848M",
    elevationLossFt: "",
    elevationLossMeters: "",
    bestHikingWindow: "June through September",
    bestHikingWindowAverageLowTemp: "",
    bestHikingWindowAverageHighTemp: "",
    recommendedTimeSpent: "3-5 Days",
    recommendStartingSpot: "Paint Pots trail head",
    recommendedFinishingSpot: "Floe Lake trail head",
    recommendStartingSpotCoordinates: "",
    recommendedEndingSpotCoordinates: "",
    isItCommonToHitchHike: "yes",
    recommendRoute: {
        day1: "Sleep at __ campground",
        day2: "Sleep at __ campground",
        day3: "Sleep at __ campground",
        day4: "Sleep at __ campground",
    },
    highlightsAndFeatures: "",
    howFastDoPermitsSellOut: "Usually within the first hour of being available",
    permitGatheringInstructions: "Log on early and get in the queue. Go as fast as you can!",
    permitWebsite: "https://reservation.pc.gc.ca/Banff,KootenayandYohoBackcountry",
    linkToOfficialWebsite: "https://www.pc.gc.ca/en/pn-np/bc/kootenay/activ/arrierepays-backcountry",
    waterSupplyInformation: "",
    maxElevation: "",
    lowestElevation: "",
    areThereBears: "",
    wildlifeSpottingOpportunities: "",
}

]